theme: texture

texture:
  title: St√©phane Cerveau
  tagline: Senior Software Engineer - Consultant @ Collabora
  date_format: "%b %-d, %Y"

  social_links:
    github:  dabrain34
    linkedIn: in/stephane-cerveau-8a53ab2/
  style: blue
